### PR TITLE
feat: sonarqube pipeline

### PR DESCRIPTION
**Pull request by GabyGV-GGV**
#### Resolved task/US: ([CS-17 [SP-0] : Continuous integration](https://app.clickup.com/t/868a9pea1))
* * * *

## What's in this pull request?

To implement we use an Azure virtual machine and inside the virtual machine we install Sonarqube, thus creating as a second step the pipeline to test the new code within Sonarqube.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
```
$ git clone --depth=1 --branch "chore/cs-17/continuous-integration" https://github.com/SoftDevSix/Argos
$ ./sonar-analyze-v1.0.sh
``` 
The command './sonar-analyze-v1.0.sh' is a custom script that you can download [here](https://jalafoundation.sharepoint.com/:u:/s/Progra6-SoftwareDevelopment/EfI-_eJ7RLNFqcyRjwEgNMcBAPxb96fY8bjEwUb585Y_Ig?e=cRNTna). Please use 'chmod 744 ./sonar-analyze-v1.0.sh' to grand execution perms.  That command should send an analysis request to the server.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by zamoranoalicia — APPROVED** [review]
LGTM, please do an squash of your commits before merging

**Comment by ignacio-villarroel-jalafund** [comment]
Teste PR with  the current build (commit: [chore: fix-coverage-report](https://github.com/SoftDevSix/Argos/pull/4/commits/97cabe429ec73128bb4ba71b73d279e29778a604)) October 29 2024
Screenshot from 2024-10-29 20-48-25

**Review by alex-paca-jalafund — CHANGES_REQUESTED** [review]
using the git clone --depth = 1 its making:
Screenshot from 2024-10-30 08-26-58
It seems that you have not generated a complete test coverage report due to the missing test report files (Junit), and in the PR it's added a test ArgosApplicationTest.java, but now i see that its working on the azure cloud machine, its updating each time we use sh file.

if I doesnt use the --depth= 1 and follow the typical flow just making git clone to argos project and moving to this branch making the sh steps:

Screenshot from 2024-10-30 08-10-07

**Review by zamoranoalicia — APPROVED** [review]
LGTM

**Comment by GabyGV-GGV** [comment]
@alex-paca-jalafund  I can't replicate that error, using the normal git flow, please check again

**Comment by alex-paca-jalafund** [comment]
> @alex-paca-jalafund I can't replicate that error, using the normal git flow, please check again

yep i make the same steps for replicate now and its working normaly im marking my change request has resolved since the issue its not replicable.

**Review by alex-paca-jalafund — APPROVED** [review]

**Comment by zrock-dev** [comment]
Since both reviewers have approved the latest changes I'm merging this branch.

**Pull request merged**
