### PR TITLE
feat: add rulesService and test

### PR DESCRIPTION
**Pull request by sebastian-barra-jalafund**
#### Resolved task: ([013-2 Business logic](https://app.clickup.com/t/868ajdwkw))
* * * *

## What's in this pull request?
Adds the RulesService class along with comprehensive unit tests for all validation scenarios. The RulesService processes rules based on different criteria, stores valid rules, and logs validation errors when rules are invalid.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
Using JUnit unit tests to verify each validation rule. Each rule's conditions were tested for valid and invalid cases, ensuring 100% coverage compliance with SonarQube.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by zrock-dev — CHANGES_REQUESTED** [review]
Exception messages are in spanish, please update them to english.

**Comment by sebastian-barra-jalafund** [comment]
> Exception messages are in spanish, please update them to english.

comments were changed to english

**Comment by sebastian-barra-jalafund** [comment]
> Exception messages are in spanish, please update them to english.

comments were changed to english

**Comment by sebastian-barra-jalafund** [comment]
> Exception messages are in spanish, please update them to english.

comments were changed to english

**Review by zrock-dev — APPROVED** [review]
good job

**Pull request merged**
