### PR TITLE
chore: sql database configuration

### PR DESCRIPTION
**Pull request by teran-joseluis**
#### Resolved task/US: SQL Database Configuration
* * * *

## What's in this pull request?

This PR set the required database configuration for different environments given, such as **dev**, **stage**, and **prod**

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Build Configuration Change

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by zamoranoalicia — APPROVED** [review]
LGTM

**Review by fabian-romero-jalafund — APPROVED** [review]
Good

**Review by samuel-escalera-jalafund — APPROVED** [review]
Good job

**Review by zamoranoalicia — APPROVED** [review]
LGTM

**Pull request merged**
